# Generated by Django 4.2.2 on 2023-06-22 15:58

import django.core.validators
from django.db import migrations, models
import exam_prep.web.validators


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(null=True, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(15), exam_prep.web.validators.alpha_num]),
        ),
    ]
